== Apache Kafka : Tips & Tricks que j'aurais aimé connaître plus tôt..

>  vendredi 30 juin, 10:10 - 11:00

link:https://sunny-tech.io/sessions/apache-kafka-tips-tricks-que-j[Lien]
link:https://sunny-tech.io/speakers/arnaud-esteve[Arnaud Esteve]

=== Abstract

Vous êtes vous déjà retrouvé avec 2000 topics créés en 3 minutes ? Avec un cluster Kafka totalement innondé de connexions ? Un producer aux performances désastreuses, peut-être ?

Non ? Nous si !

Je vous propose, à travers différentes expériences : douloureuses à vivre mais amusantes à entendre de parcourir ensemble une liste des petits (ou gros) trucs que j'aurais aimé savoir, ou comprendre, plus tôt.

On en profitera également pour balayer les questions les plus fréquentes qu'on peut se poser, ou qu'on a pu me poser : Quel format pour mes messages ? Combien de partitions ? Le tout en essayant, quand c'est possible, de dédramatiser.

Idéal si vous connaissez déjà un peu Kafka (les concepts de base), mais n'avez pas (encore !) un niveau avancé. Peut également convenir si vous voulez vous lancer avec Kafka. Les utilisateurs plus avancés pourraient aussi apprendre quelques bonnes pratique, et se retrouveront très certainement dans certaines des expériences racontées.

Les astuces sont un peu plus orientées pour les développeurs, mais les Ops peuvent être intéressés également (options de configuration, compression, etc.).

=== Notes

Mes notes sur le talk
