= SunnyTech 2023

// Handling GitHub admonition blocks icons
:icons: font
:imagesdir: ./images
:source-highlighter: highlightjs
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== Jeudi

:leveloffset: +1

== CodeCarbon : Comment mesurer l’impact CO2 de vos projets?

> jeudi 29 juin, 14:00 - 14:50

link:https://sunny-tech.io/sessions/codecarbon-comment-mesurer-lim[Lien]
link:https://sunny-tech.io/speakers/benoit-courty[Benoit Courty]
link:https://sunny-tech.io/speakers/amine-saboni[Amine Saboni]
link:https://www.youtube.com/watch?v=GxwEa7wydWI&list=PLz7aCyCbFOu-5OE0ajDUVjlqBFq1y9XiQ&index=20[Video]

=== Abstract

"Ce qui ne se mesure pas n'existe pas" disait Niels Bohr.

Le numérique compte pour 2,5% de l’empreinte carbone de la France, nous disent l’ADEME et l’ARCEP mais qu’en est-il de nos impacts individuels en tant que développeur ou organisation? Quel est l’impact CO2 des puissances de calculs que nous utilisons au quotidien? De ce sur quoi nous avons réellement la main?

CodeCarbon est un package python open source qui estime cet impact. C’est un outil léger permettant de se construire des ordres de grandeurs sur l’impact de sa pratique professionnelle et d’aller au-delà des chiffres globaux et parfois fourre-tout lancés dans les médias; pour que chaque développeur puisse prendre la main sur son impact carbon et ouvrir la discussion.

Pensé d’abord pour mesurer l’empreinte des modèles de Machine Learning et d’IA, CodeCarbon a évolué et s’adapte désormais à d’autres cas d’usages, nous vous en ferons la démonstration pour que vous puissiez vous approprier facilement cet outil.

=== Notes

Outil python mesure CO2

Fabrication toujours plus coûteux

Ordre de grandeur de l'ordre de x100 stats faussées streaming video par ex

Electrictymap origine énergie pour choix serveur

Modèle ML coûteux en CO2

Taxe carbone

Modèle bloom français entraînement

Consommation rapl unix pour suivi énergie

NVIDIA smi suivi gpu

Mlco2 calcultor

Code carbon monitor pour monitor process hors python

Comparatif entraînement modèle selon consommation cpu

Scaphandre hubblo

Mesure via agent

Low impact layout site selon consommation énergie lowtech mag'


:leveloffset!:
:leveloffset: +1

== Kustomizons nos déploiements K8S avec style 🤩 !

>  jeudi 29 juin, 18:00 - 18:20

link:https://sunny-tech.io/sessions/kustomizons-nos-deploiements-k[Lien]
link:https://sunny-tech.io/speakers/kevin-davin[Kevin Davin]
link:https://www.youtube.com/watch?v=Bdnaf9UGyVM&list=PLz7aCyCbFOu-5OE0ajDUVjlqBFq1y9XiQ&index=16[Video]

=== Abstract

Et si l'on rebootait le système de templating YAML dans le monde Kubernetes?

Venez découvrir Kustomize, une alternative sur-puissante pour "templatiser vos applications" sans pour autant rendre illisible vos fichiers YAML 🎉. Nous verrons ensemble comment organiser le développement pour permettre l'extension, l'héritage et autres modifications de déploiement avec Kustomize.

A la fin de ce talk, vous serrez à même de déployer une app dans Kube, dans différents environments, de manière simple, lisible et accessible depuis la ligne de commande kubectl 😍 !

=== Notes

Ressources relatives

Configmap generator

Notion de checksum configmap built in

Prefix suffix => géré auto par kustomize et permet de redéployer les ressources dépendantes

Registre d'image dans kustomize

Peut s'intégrer avec helm

Components optin ressources basé dans les childs

:leveloffset!:
:leveloffset: +1

== Laissez tomber vos Dockerfile, adoptez un buildpack !

> jeudi 29 juin, 10:10 - 11:00

link:https://sunny-tech.io/sessions/laissez-tombez-vos-dockerfile-[Lien]
link:https://sunny-tech.io/speakers/julien-wittouck[Julien Wittouck]
link:https://www.youtube.com/watch?v=2Zo34sXsMxU&list=PLz7aCyCbFOu-5OE0ajDUVjlqBFq1y9XiQ&index=2[Video]

=== Abstract

Depuis plusieurs années maintenant, Docker est utilisé par toute l'industrie de l'IT pour packager et déployer des applications.

Bien que l'écriture d'un Dockerfile soit facile, la construction d'images OCI/Docker reste un exercice compliqué:

- optimisation des layers de l'image
- bonne gestion des processus Linux
- séparation des phases de build et de run des images
- bonnes pratiques de sécurité

Pire, lorsqu'une faille de sécurité est détecté dans une layer basse (distribution ou runtime) d'une image applicative, il faut alors potentiellement reconstruire plusieurs dizaines ou centaines d'images pour y intégrer les version patchées.

Dans ce talk, nous apprendrons comment les buildpacks permettent de construire des images OCI/Docker sans Dockerfile et bénéficier des bonnes pratiques issues de la communauté open-source.

Nous verrons :

- ce qu'est une image OCI, une layer, et comment Docker les construit
- comment analyser le contenu des layers d'une image OCI, et ce qui ne va pas dans les images que nous construisons au quotidien
- ce qu'est un buildpack et comment un buildpack construit une image OCI
- avec une démo, comment utiliser un buildpack proposé par la communauté open-source pour contruire une image OCI contenant une application NodeJS ou Java optimisée
- enfin, nous verrons comment les buildpacks proposent de rebaser des image, et nous permettre de patcher en masse des images applicatives pour corriger des failles de sécurité, sans rebuilder complètement nos images !

Ce talk est donc à destination des Ops et des Devs qui manipulent Docker au quotidien.

À la sortie de ce talk, je devrai vous avoir convaincu d'abandonner vos Dockerfile et d'expérimenter les buildpacks !

=== Notes

Oci images

Different point de vue sécu ops dev

Json tar gz => manifest image conteneur

Dive docker image inspect

Buildpacks.io

Crée par heroku paas => cnb cncf

2 binaires detect + build

Builder qui crée image via script lifecycle

Baketo builder communautaire

Conflit de builder?

Utilise par cloud builder pour serverless

Knative buildpacks utilise

Riff netlify

Sbom => software bill of material (doc sécu)

Rebase image possible pour upgrade java par exemple

Tekton

:leveloffset!:
:leveloffset: +1

== Plongeons dans la création d'un provider Terraform

> jeudi 29 juin, 11:20 - 12:10

link:https://sunny-tech.io/sessions/plongeons-dans-la-creation-dun[Lien]
link:https://sunny-tech.io/speakers/horacio-gonzalez-lostinbrittany[Horacio Gonzalez]
link:https://sunny-tech.io/speakers/aurelie-vache[Aurélie Vache]
link:https://www.youtube.com/watch?v=vwUyfPxCEVA&list=PLz7aCyCbFOu-5OE0ajDUVjlqBFq1y9XiQ&index=40[Video]

=== Abstract

Ces derniers temps, quand on pense à l'Infrastructure as Code (IaC), un outil semble se démarquer et est devenu un standard de facto : Terraform.

Avec Terraform, vous pouvez facilement créer, modifier et versionner l'ensemble de votre infrastructure en utilisant des providers natifs à Terraform ou des providers personnalisés.

Mais parfois, il n'y a pas de provider pour l'infrastructure que vous voulez utiliser, pas même un petit bout de code sans aucune référence dans un coin perdu d'Internet. La seule chose que l'infrastructure propose, c'est une API REST. Que pouvez-vous faire ? Revenir aux opérations manuelles ? Créer vos propres scripts bash pour piloter vos infras ?

Dans cette conférence, Horacio et Aurélie vous montreront, étape par étape, comment passer d'une API d'infrastructure à un provider Terraform entièrement fonctionnel mais léger. En prenant comme base une API REST, ils expliqueront les bases de la création du provider, donneront quelques conseils sur la façon de faire une architecture du provider simple mais efficace et vous montreront le code en action.

Vont-ils réussir cette nouvelle mission ? :-D

=== Notes

Pets server vs farm server => IAC

Provider = wrapper api

Taskfile = make "moderne"

Utiliser template hashicorp pour création provider

Enlever lock si pas de changement de version durant dev sinon pas update => durant le développement

Tfplugins docs generator doc

:leveloffset!:
:leveloffset: +1

== Un solveur de contraintes à la rescousse de SunnyTech

>  jeudi 29 juin, 16:20 - 17:10

link:https://sunny-tech.io/sessions/n-solveur-de-contraintes-a-la[Lien]
link:https://sunny-tech.io/speakers/eric-taix[Eric Taix]

=== Abstract

Sunnytech c'est 5 tracks et 50 talks sur 2 jours soit environ 10+53 possibilités de planification différentes, de quoi faire tourner la tête !

Les problèmes de planification sont nombreux et très courants (gestion des emplois du temps, optimisation des tournées, ...) et ils sont souvent très durs, voir impossibles à résoudre dans un temps polynomial, ce qui les classent dans les problèmes de type NP (Non determinist Problem).

Sans besoin de connaissance mathématique préalable, vous découvrirez dans ce talk OptaPlanner, un solveur de contraintes open-source de JBoss. Ce framework vous permettra de répondre simplement à ces problèmes de planification et de trouver une solution en un temps record quelque soit vos contraintes.

Nous planifierons même en live l'édition 2023 de SunnyTech au risque de tous disparaitre, remplacé par un autre talk...

=== Notes

Mes notes sur le talk

:leveloffset!:
== Vendredi

:leveloffset: +1

== REX: Une infrastructure Serverless de zéro, en Rust

>  vendredi 30 juin, 09:00 - 09:50

link:https://sunny-tech.io/sessions/rex-une-infrastructure-serverl[Lien]
link:https://sunny-tech.io/speakers/alexandre-burgoni[Alexandre Burgoni]

=== Abstract

Function As A Service et Serverless, deux mots-clés qui donnent des étoiles dans les yeux. Mais avez-vous déjà vu la face cachée de ces systèmes du quotidien ?

Au travers de deux projets: "RIK" et "Morty", nous irons en profondeur des composants d'une infrastructure FaaS : load balancer, front-end, runtime, software-defined network, scheduling, builder et j'en passe. Histoire de vous aider à y voir plus clair la prochaine fois que vous appellerez une fonction.

RIK et Morty ? Pendant plusieurs mois nous avons développé "RIK", un orchestrateur de conteneurs et VMs en Rust. Et ce n'était pas uniquement pour concurrencer Kubernetes, mais aussi pour permettre de faire l'expérimentation d'une infrastructure serverless "Morty", from scratch et toujours en Rust ! Et bonne nouvelle, ces deux projets sont complètement Open-Source !

=== Notes

Faaz orchestre

Rex projet cours Polytech

Rik rust in kube open source

Micro vm pour isoler kerbel

Firecracker microvm

Développer firepilot pour sdk rust

Utilisation rootfs via extract docker (build docker file)

Morty faaz runtime pour créer rootfs

Création agent dans Rootfs pour interaction avec microvm via socket http + telemtry

Controller point d'entrée load balancer function manager scheduler

Demo live wordle

:leveloffset!:
:leveloffset: +1

== Le numérique c’est pour tout le monde… ou pas !

> vendredi 30 juin, 10:10 - 11:00

link:https://sunny-tech.io/sessions/le-numerique-cest-pour-tout-le[Lien]
link:https://sunny-tech.io/speakers/iris-naudin[Iris Naudin]
link:https://sunny-tech.io/speakers/cecile-freydfoucault[Cécile Freyd-Foucault]

=== Abstract

Zones sans réseau, sites pas accessibles, télécommandes infernales … saviez-vous que 66% des utilisateurs sont exclus de vos dispositifs ?

Vous voulez vivre dans un monde où les portes s’ouvrent dans le sens où elles sont censées s’ouvrir ? Où vos parents sont autonomes pour refaire leur carte grise en ligne ? Où (folie !) un site se charge en moins de 25 secondes même avec une mauvaise connexion ?

Suivez-nous pour un tour d’horizon anti-exclusion : accessibilité, technique, complexité et contenu !

=== Notes

1/3 exclus numérique

80% handicap invisible

Pas de cadre pour l'inclusion mais pénal pour discrimination si pas conforme

Couvertures réseau ARCEP

Formation pro accessibilité insuffisante

Biais jeu de données

Biais cognitif

Biais auto complaisance  Projection

Pour changer

Penser cas personnes oubliée lors conception

Alt image

Microsoft désign toolkit

Accessibility annotations kit

Français facile à lire et comprendre falc

https://github.com/cecilefreyd/numerique_inclusif_ressources

Rgaa obligatoire pour boîte >2m CA en 2025

:leveloffset!:
:leveloffset: +1

== Imaginez un monde sans mot de passe 🔑

>  vendredi 30 juin, 14:00 - 14:20

link:https://sunny-tech.io/sessions/imaginez-un-monde-sans-mot-de-[Lien]
link:https://sunny-tech.io/speakers/raphael-delplanque[Raphael Delplanque]

=== Abstract

Description pour convaincre d'assister au talk :

T'en as marre de rentrer de vacances et de te demander quel est ton mot de passe ? Marre de passer du temps avec le support qui te pose 50 questions avant d'arriver à réinitialiser ton mot de passe. Souviens toi que tu as aussi perdu tes accès à Facebook et ton ancienne adresse Yahoo comme ça… Et si on changeait tout ça ?

L'idée de cette session c'est de montrer les cas d'usages qu'on a aujourd'hui autour de l'authentification (pro et perso), de mettre en avant les forces et faiblesses des solutions existantes, de discuter de l'enjeu du mot de passe et du temps qu'il lui reste à vivre face aux nouvelles solutions d'authentification. Démonstration de comment lier et utiliser une Yubikey avec son compte Microsoft personnel. Des clés seront offertes pour l'occasion ;-)
Message pour les organisateurs :

L'idée tu l'as compris c'est de discuter d'une solution disruptive, une nouvelle méthode de connexion qui va bouleverser le monde de l'authentification. Ce facteur d'authentification c'est la Yubikey, un coffre-fort numérique qui permet de stocker vos identités qu'elles soient professionnelles ou personnelles. On l'appelle souvent, le couteau suisse de l'authentification moderne. Au-delà de sa polyvalence, elle a le mérite d'être ultra résistante aux épreuves de la vie courante et comparé aux solutions d'authentifications existantes c'est le meilleur compromis sécurité, stabilité, UX ( expérience utilisateur ) et coût d'acquisition. La YubiKey est interopérable nativement sur la plupart des systèmes d'exploitation et applications, fonctionne sans applications tierces, sans licences et est agnostique du réseau et des batteries. La Yubikey va permettre de venir supprimer les mots de passe sur l'ensemble des applications et systèmes pris en charge (Liste en PJ).

En route vers la passwordless ! 🛣️

=== Notes

Yubikey

Compatible natif OS Linux / Win

Ouverture session Accès office Vpn connexion linux signature code avec


:leveloffset!:
:leveloffset: +1

== Pourquoi le CSS Ca Saoule Souvent

>  vendredi 30 juin, 11:20 - 12:10

link:https://sunny-tech.io/sessions/pourquoi-le-css-ca-saoule-souv[Lien]
link:https://sunny-tech.io/speakers/alberic-trancart[Albéric Trancart]

=== Abstract

Tu t’es déjà senti frustré·e par le CSS ? Que ce soit pour centrer les choses verticalement ou utiliser des hacks magiques pour obtenir ce qu’on veut… soit on a le “gène CSS”, soit on ne l’a pas. Les devs qui aiment le CSS semblent plus être l’exception que la règle.

Mais n’aie pas peur ! Ce n’est pas une fatalité.

Après avoir formé des douzaines de développeurs à CSS sur les 5 dernières années, j’ai fini par comprendre ce qui n’allait fondamentalement pas avec le CSS. Et je suis prêt à te le partager. Au programme :

- une analyse d’où vient vraiment cette frustration
- des astuces actionnables pour level up rapidement son niveau en CSS
- comment apprendre les bons modèles mentaux pour intégrer des designs complexes

Qui sait ? Tu finiras peut-être même par aimer ça !

=== Notes

Démystifier CSS => Magie noire

Pourquoi compliqué ? Car considéré par comme language et que mal compris : intention vocabulaire grammaire

Maquette moyen imparfait de transmettre information

CSS grammaire

Code doit respecter intention : variable calc stylelint

Stacking context z index

RadixUI composant accessibilité

Cssdojo.dev


:leveloffset!:
:leveloffset: +1

== Typesafe all the things: typage fort de la base de données jusqu'au client gràce à TypeScript, tRPC & prisma

>  vendredi 30 juin, 15:10 - 16:00

link:https://sunny-tech.io/sessions/typesafe-all-the-things-typage[Lien]
link:https://sunny-tech.io/speakers/benjamin-legrand[Benjamin Legrand]

=== Abstract

Vous maintenez des interfaces synchronisées entre votre back et votre front ? c'est lourd non ?

Peut-être avez vous besoin d'une étape de génération lors d'un changement de modèle de données de vos API's ?

Le saviez-vous ? : on peut aujourd'hui se passer de tout cela.

Découvrez une stack technique utilisant la puissance de typescript au service de l'expérience développeur et de la simplicité:

- tRPC pour une API et son client sans schémas ni génération de code.
- prisma pour un ORM supportant de nombreuses bases de données et orienté typescript first.


=== Notes

Prisma auto génération type + ORM // introspection

Single source truth => Mais attention scale

Drizzle alternative

Trpc

- Query (get)
- Mutation (post)
- Websocket (subscription)

Permet validation objet JS avec zod

Typescript generic

Serialization superjson

Réconcilier équipe front back

Openapi generator code

Monorepo > multi repo

Monorepo.tools

Inference type typescript

:leveloffset!:
:leveloffset: +1

== Votre propre kube as a service ? Une aventure dont vous êtes le héros...

>  vendredi 30 juin, 16:20 - 17:10

link:https://sunny-tech.io/sessions/votre-propre-kube-as-a-service[Lien]
link:https://sunny-tech.io/speakers/louis-tournayre[Louis Tournayre]

=== Abstract

À la suite à votre succès dans la mise en place de GitOps dans kubernetes, votre équipe ne jure plus que par kube et ArgoCD.

Mais un nouveau péril approche : la direction veut maintenant que la voix du GitOps embrasse tous les projets. Vous êtes sommé d'héberger et de gérer les futurs projets qui ne sauraient tarder à envahir vos clusters. Et vous avez très peu de temps, la direction a annoncé dans 42 informatik qu'elle était cloud ready.

Saurez-vous trouver des solutions pour héberger les nouvelles applications, partager vos infrastructures et vous protéger d'elles ?

Cette aventure sera interactive, soyez prêt à assumer vos choix, vous apprendrez de vos erreurs comme de vos succès, et peut être arriverez vous à proposer une solution d'hébergement multi-tenant.

*4ème de couverture :

Cette présentation est destinée aux aventuriers avec quelques connaissances de k8s et se posant des questions d'isolations et de partage de ressources avec kubernetes. Différents choix s'offriront à vous, prendrez-vous les bonnes options ? Arriverons-nous à temps à répondre aux attentes de la direction ?

=== Notes

Aventure héro partie 2 d'un talk précédent.

Capi fourni par k8s pour provisionner cluster. Nécessite un cluster d'admin

Cluster ctl

Kubectl konfignimport save pour merge kubeconfig  (plugin krew)

:leveloffset!:
:leveloffset: +1

== Vous devriez utiliser un serveur de configuration

>  vendredi 30 juin, 14:30 - 14:50

link:https://sunny-tech.io/sessions/vous-devriez-utiliser-un-serve[Lien]
link:https://sunny-tech.io/speakers/olivier-bourgain[Olivier Bourgain]

=== Abstract

Durant les ages sombres de l'informatique, les développeurs demandaient aux sysadmins via des tickets Jira de modifier des fichiers de configuration, en espérant donner une description assez précise des changements à effectuer. Ensuite, le sysadmin ouvrait un shell sur le serveur, éditait le fichier avec vi et redémarrait l'application en croisant les doigts. Qui n'a jamais eu un incident à cause d'une erreur dans cette procédure ? Comment éviter les problèmes ?

Une solution est de retirer autant d'étapes que possible et automatiser le reste. Imaginons un instant traiter la configuration comme le code. Il faut faire des pull requests, avoir la review, passer la CI. On a aussi un historique des modifications, la facilité de rollback etc.

=== Notes

Mirakl

Kube déploiement des applis clients

Spring cloud config boot server client pour gitops à la main 2017

Poll périodique de confgi dépôt git

Argocd à la main via api http

Donne accès à toute équipe via PR pour autonomie via feature flag

Serveur config au démarrage appli fetch config

Problème boot appli si pas dispo

Tout peut pas être géré avec (postgres config jvm...)

:leveloffset!:
