== FoundationDB : le secret le mieux gardé des nouvelles architectures distribuées !

>  jeudi 29 juin, 14:00 - 14:50

link:https://sunny-tech.io/sessions/foundationdb-le-secret-le-mieu[Lien]
link:https://sunny-tech.io/speakers/steven-le-roux[Steven Le Roux]
link:https://sunny-tech.io/speakers/pierre-zemb[Pierre Zemb]

=== Abstract

Savez-vous quel est le point commun entre Apple, Snowflake, VMWare et Datadog ? Ces entreprises partagent le même ingrédient : FoundationDB

FoundationDB est une base de données distribuée, open-source, souvent cachée dans l'infrastructure bas-niveau permettant de gérer des transactions distribuées ACID.

Durant ce talk, nous vous proposons une découverte de cette base de données si peu connue. Vous découvrirez l'histoire du projet, ses garanties transactionnelles aussi fortes que Spanner, ainsi que sa robustesse opérationnelle. Nous ferons aussi un retour d'expérience sur le développement d'applications par-dessus FoundationDB.

=== Notes

Mes notes sur le talk
