== Laissez tomber vos Dockerfile, adoptez un buildpack !

> jeudi 29 juin, 10:10 - 11:00

link:https://sunny-tech.io/sessions/laissez-tombez-vos-dockerfile-[Lien]
link:https://sunny-tech.io/speakers/julien-wittouck[Julien Wittouck]
link:https://www.youtube.com/watch?v=2Zo34sXsMxU&list=PLz7aCyCbFOu-5OE0ajDUVjlqBFq1y9XiQ&index=2[Video]

=== Abstract

Depuis plusieurs années maintenant, Docker est utilisé par toute l'industrie de l'IT pour packager et déployer des applications.

Bien que l'écriture d'un Dockerfile soit facile, la construction d'images OCI/Docker reste un exercice compliqué:

- optimisation des layers de l'image
- bonne gestion des processus Linux
- séparation des phases de build et de run des images
- bonnes pratiques de sécurité

Pire, lorsqu'une faille de sécurité est détecté dans une layer basse (distribution ou runtime) d'une image applicative, il faut alors potentiellement reconstruire plusieurs dizaines ou centaines d'images pour y intégrer les version patchées.

Dans ce talk, nous apprendrons comment les buildpacks permettent de construire des images OCI/Docker sans Dockerfile et bénéficier des bonnes pratiques issues de la communauté open-source.

Nous verrons :

- ce qu'est une image OCI, une layer, et comment Docker les construit
- comment analyser le contenu des layers d'une image OCI, et ce qui ne va pas dans les images que nous construisons au quotidien
- ce qu'est un buildpack et comment un buildpack construit une image OCI
- avec une démo, comment utiliser un buildpack proposé par la communauté open-source pour contruire une image OCI contenant une application NodeJS ou Java optimisée
- enfin, nous verrons comment les buildpacks proposent de rebaser des image, et nous permettre de patcher en masse des images applicatives pour corriger des failles de sécurité, sans rebuilder complètement nos images !

Ce talk est donc à destination des Ops et des Devs qui manipulent Docker au quotidien.

À la sortie de ce talk, je devrai vous avoir convaincu d'abandonner vos Dockerfile et d'expérimenter les buildpacks !

=== Notes

Oci images

Different point de vue sécu ops dev

Json tar gz => manifest image conteneur

Dive docker image inspect

Buildpacks.io

Crée par heroku paas => cnb cncf

2 binaires detect + build

Builder qui crée image via script lifecycle

Baketo builder communautaire

Conflit de builder?

Utilise par cloud builder pour serverless

Knative buildpacks utilise

Riff netlify

Sbom => software bill of material (doc sécu)

Rebase image possible pour upgrade java par exemple

Tekton
