== Sécurisons nos utilisateurs grâce au Mozilla Observatory

>  jeudi 29 juin, 15:10 - 16:00

link:https://sunny-tech.io/sessions/securisons-nos-utilisateurs-gr[Lien]
link:https://sunny-tech.io/speakers/antoine-caron[Antoine Caron]

=== Abstract

Assurer la sécurité d'une application web est une tâche complexe qui nécessite une attention particulière. Il est difficile de savoir si son site web est suffisamment protégé et s'il respecte les normes de sécurité habituelles. Pour aider les propriétaires de sites web à évaluer leur sécurité, la fondation Mozilla propose un outil d'audit gratuit qui permet de vérifier rapidement si son site web respecte un ensemble de règles de sécurité.

Cependant, il est important de noter que l'utilisation de l'outil d'audit ne suffit pas à garantir la sécurité de votre site web. Si toutefois les propriétaires de sites web suivaient les pratiques de sécurité recommandées, le web serait déjà beaucoup plus sûr pour tous.

Dans le cadre d'un livecoding, je vous invite à suivre mes instructions pour améliorer la sécurité de votre site web. Nous allons travailler ensemble pour passer votre site web d'un niveau F à un niveau A+ dans le Mozilla Observatory.

=== Notes

Mes notes sur le talk
